media:
  input: src/media
  output: /media

content:
  - name: posts
    label: Posts
    path: src/_posts
    type: collection
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: body
        label: Body
        type: rich-text
        required: true
    view:
      fields: [title, date]
      primary: title
      sort: [date, title]
      default:
        search: ''
        sort: date
        order: desc

  - name: community
    label: Community
    path: _data/community.yml
    type: file
    fields:
      - name: header
        label: Header
        type: string
        required: true
      - name: subheader
        label: Subheader
        type: string
        required: true
      - name: feature1
        label: Feature 1
        type: string
        required: true
      - name: description1
        label: Description 1
        type: text
        required: true
      - name: title1
        label: Title 1
        type: string
        required: true
      - name: feature2
        label: Feature 2
        type: string
        required: true
      - name: description2
        label: Description 2
        type: text
        required: true
      - name: title2
        label: Title 2
        type: string
        required: true
      - name: feature3
        label: Feature 3
        type: string
        required: true
      - name: description3
        label: Description 3
        type: text
        required: true
      - name: title3
        label: Title 3
        type: string
        required: true

  - name: format
    label: Format
    path: _data/format.yml
    type: file
    fields:
      - name: header
        label: Header
        type: string
        required: true
      - name: subheader
        label: Subheader
        type: string
        required: true
      - name: features
        label: Features
        type: object
        list: true
        fields:
          - name: header
            label: Header
            type: string
            required: true
          - name: title1
            label: Title 1
            type: string
            required: true
          - name: title2
            label: Title 2
            type: string
            required: true
          - name: title3
            label: Title 3
            type: string
            required: true
          - name: title4
            label: Title 4
            type: string
            required: true

  - name: events
    label: Events
    path: _data/events.yml
    type: file
    fields:
      - name: header
        label: Header
        type: string
        required: true
      - name: subheader
        label: Subheader
        type: string
        required: true
      - name: features
        label: Features
        type: object
        list: true
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: date
            label: Date
            type: string
            required: true
          - name: header
            label: Header
            type: string
            required: true
          - name: subheader
            label: Subheader
            type: string
            required: true
          - name: place
            label: Place
            type: string
            required: true
          - name: button
            label: Button
            type: string
            required: true

  - name: footer
    label: Footer
    path: _data/footer.yml
    type: file
    fields:
      - name: header
        label: Header
        type: string
        required: true
      - name: subheader
        label: Subheader
        type: string
        required: true
      - name: footer
        label: Footer
        type: object
        list: true
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: option1
            label: Option 1
            type: string
            required: true
          - name: option2
            label: Option 2
            type: string
            required: true
          - name: option3
            label: Option 3
            type: string
            required: true
          - name: option4
            label: Option 4
            type: string
            required: true

  - name: statistics
    label: Statistics
    path: _data/statistics.yml
    type: file
    fields:
      - name: header
        label: Header
        type: string
        required: true
      - name: subheader
        label: Subheader
        type: string
        required: true
      - name: header1
        label: Header 1
        type: string
        required: true
      - name: subheader1
        label: Subheader 1
        type: string
        required: true
      - name: header2
        label: Header 2
        type: string
        required: true
      - name: subheader2
        label: Subheader 2
        type: string
        required: true
      - name: header3
        label: Header 3
        type: string
        required: true
      - name: subheader3
        label: Subheader 3
        type: string
        required: true

  - name: hero
    label: Hero
    path: _data/hero.yml
    type: file
    fields:
      - name: title
        label: Title
        type: object
        list: true
        fields:
          - name: character
            label: Character
            type: string
            required: true
          - name: color
            label: Color
            type: string
            required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: country
        label: Country
        type: string
        required: true
      - name: headline
        label: Headline
        type: object
        fields:
          - name: part1
            label: Part 1
            type: string
            required: true
          - name: part2
            label: Part 2
            type: string
            required: true
      - name: buttons
        label: Buttons
        type: object
        list: true
        fields:
          - name: text
            label: Text
            type: string
            required: true
          - name: link
            label: Link
            type: string
            required: true

  - name: about
    label: About
    path: _data/about.yml
    type: file
    fields:
      - name: header
        label: Header
        type: string
        required: true
      - name: subheader
        label: Subheader
        type: string
        required: true
      - name: feature1
        label: Feature 1
        type: string
        required: true
      - name: description1
        label: Description 1
        type: text
        required: true
      - name: feature2
        label: Feature 2
        type: string
        required: true
      - name: description2
        label: Description 2
        type: text
        required: true

  - name: team
    label: Team
    path: _data/team.yml
    type: file
    fields:
      - name: header
        label: Header
        type: string
        required: true
      - name: subheader
        label: Subheader
        type: string
        required: true
      - name: title1
        label: Title 1
        type: string
        required: true
      - name: description1
        label: Description 1
        type: text
        required: true
      - name: title2
        label: Title 2
        type: string
        required: true
      - name: description2
        label: Description 2
        type: text
        required: true
      - name: title3
        label: Title 3
        type: string
        required: true
      - name: description3
        label: Description 3
        type: text
        required: true
      - name: title4
        label: Title 4
        type: string
        required: true
      - name: description4
        label: Description 4
        type: text
        required: true
      - name: title5
        label: Title 5
        type: string
        required: true
      - name: description5
        label: Description 5
        type: text
        required: true
      - name: title6
        label: Title 6
        type: string
        required: true
      - name: description6
        label: Description 6
        type: text
        required: true

components:
  hero:
    label: Hero Section
    type: object
    fields:
      - name: headline
        label: Headline
        type: text
        required: true
      - name: cover
        label: Cover Image
        type: image
  email:
    label: Email Address
    type: string
    pattern:
      regex: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
      message: 'This must be a valid email address (e.g. hello@example.com).'
